version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./webprogramlama:/app
    env_file:
      - ./webprogramlama/.env
    command: >
      sh -c "
      npm install &&
      npx prisma migrate dev --name init &&
      npm run build &&
      npm start
      "
